name: Build docker images

on:
  push:
    branches: [ "master", "recipes" ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Docker login
        run: docker login quay.io --username $DOCKER_USER --password $DOCKER_PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cabs package
        run: pip install -e suricat-beams      

      - name: Install cult-cargo
        # replace with normal install when 0.1.4 is out
        run: pip install git+https://github.com/caracal-pipeline/cult-cargo.git

      - name: Run build and push image
        run: build-cargo -m suricat-beams/suricat/cargo/cargo-manifest.yml -a
